version: "3.9"

services:
  rabbitmq:
    image: rabbitmq

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  order:
    build: Services/Order
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Services/Order:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - rabbitmq

  redis:
    image: redis

  courier:
    build: Services/Courier
    command: python manage.py runserver 0.0.0.0:8001
#    command: gunicorn -w 12 -b 0.0.0.0:8001 Courier.wsgi
    volumes:
      - ./Services/Courier:/code
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - rabbitmq

#  courier_celery_worker:
#    build: Services/Courier
#    command: celery -A Courier worker -l INFO
#    volumes:
#      - ./Services/Courier:/code
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
#      - rabbitmq

  location_exchanger:
    build: Services/Location Exchanger
    command: python3 main.py
    volumes:
      - ./Services/Location Exchanger:/code
    ports:
      - "8005:8080"
  notificator:
    build: Services/Notificator
    command: python3 main.py
    volumes:
      - ./Services/Notificator:/code
    ports:
      - "8010:8080"